### ISSUE TITLE
Wrong file paths within Docker environment

### ISSUE THREAD

**Issue by roonie007** [antfu/nuxt-server-fn#10]
### Describe the bug

When using this module with simply running `yarn run dev` everything works perfectly, but as soon as we start using it within docker ( dev environment ), we get the wrong path on the generated files.

For example, for an app that is running inside a docker container and the whole app is mounted on this path `/usr/src/app` but the actually code on the machine is on this path  `/home/***/workspace/project`, the generated files will use the docker mounted path  `/usr/src/app`.

![image](https://github.com/antfu/nuxt-server-fn/assets/7860859/58fd7c38-9f72-49e6-a76e-63d9e1785a6a)

So maybe the solution is to use the relative path instead of the absolute path ?

### Reproduction

Any simple project with the server-fn module running inside a docker container

```yaml
version: '3.8'
services:
  app:
    image: bitnami/node:20.10.0
    working_dir: /usr/src/app
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    network_mode: host
    command: ['yarn', 'dev']
```

### System Info

```Shell
System:
  OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
  CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600K
  Memory: 21.65 GB / 27.30 GB
  Container: Yes
  Shell: 5.1.16 - /bin/bash
Binaries:
  Node: 21.7.2 - ~/.nvm/versions/node/v21.7.2/bin/node
  Yarn: 1.22.19 - /usr/bin/yarn
  npm: 10.5.0 - ~/.nvm/versions/node/v21.7.2/bin/npm
  pnpm: 8.15.4 - ~/.local/share/pnpm/pnpm
  bun: 1.1.1 - ~/.bun/bin/bun
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [ ] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
